/*
 *
 *      File            ResManager.h
 *      Description     Resource Manager
 *      Version         0.95.1007
 *      Author          Y.H Mun
 * 
 * --------------------------------------------------------------------------
 *   
 *      Copyright (C) 2011 XMSoft.
 *      Copyright (C) 2011 Blue River Ltd.
 *      Copyright (C) 2011 Blueplay Ltd. All rights reserved.
 * 
 *      Contact Email: xmsoft77@gmail.com 
 *                     chris@blueplay.co.kr
 *                     	
 */ 

#ifndef __ResManager_h__
#define __ResManager_h__

#define TRANSPARENT_COLOR			ccc4 ( 16, 16, 16, 128 )

enum EPath
{
	ePath_Null						,
	eFNT_Gothic_Bold				,
    
    eSND_BGM_Main					,
	eSND_BGM_Stage					,
	eSND_BGM_Play					,
	eSND_BGM_Versus					,
	eSND_BGM_Cartoon				,
	eSND_BGM_Win					,
	eSND_BGM_Win2					,
	eSND_BGM_Lose					,
	eSND_BGM_Lose2					,
	eSND_BGM_Ending					,
	eSND_BGM_Ladder					,

    eSND_Effect_Shuffle1			,
	eSND_Effect_Shuffle2			,
	eSND_Effect_Shuffle3			,
	eSND_Effect_Attatch1			,
	eSND_Effect_Attatch2			,
	eSND_Effect_Buck				,
	eSND_Effect_Bomb				,
	eSND_Effect_Take				,
	eSND_Effect_Heading				,
	eSND_Effect_Warning				,
	eSND_Effect_Clock				,
	eSND_Effect_Notice				,
	eSND_Effect_Turn				,
	eSND_Effect_SackSul				,
	eSND_Effect_Zock				,
	eSND_Effect_Gage				,
	eSND_Effect_Dan					,
	eSND_Effect_3Gwang				,
	eSND_Effect_5Gwang				,
	eSND_Effect_BGwang				,
	eSND_Effect_1Go					,
	eSND_Effect_3Go					,
	eSND_Effect_6Go					,
    
	eSND_Attack_Gage_Success1		,
	eSND_Attack_Gage_Success2		,
	eSND_Attack_Gage_Fail1			,
	eSND_Attack_Gage_Fail2			,
	eSND_Attack_Heading				,
	eSND_Attack_Buck				,
	eSND_Attack_Buck1				,
	eSND_Attack_Buck2				,
	eSND_Attack_Buck3				,
	eSND_Attack_BuckEat 			,
	eSND_Attack_JaBuck				,
	eSND_Attack_DaDack				,
	eSND_Attack_Zock				,
	eSND_Attack_SackSul				,
	eSND_Attack_Shake				,
	eSND_Attack_Bonus				,
	eSND_Attack_Bomb				,
	eSND_Attack_3Gwang				,
	eSND_Attack_4Gwang				,
	eSND_Attack_5Gwang				,
	eSND_Attack_BGwang				,
	eSND_Attack_Stop				,
	eSND_Attack_Stop2				,
	eSND_Attack_1Go					,
	eSND_Attack_2Go					,
	eSND_Attack_3Go					,
	eSND_Attack_4Go					,
	eSND_Attack_5Go					,
	eSND_Attack_6Go					,
	eSND_Attack_7Go					,
	eSND_Attack_8Go					,
	eSND_Attack_Godori				,
	eSND_Attack_ChoDan				,
	eSND_Attack_HongDan				,
	eSND_Attack_ChungDan			,
	eSND_Attack_ChongTong			,

	eSND_Harm_Buck					,
	eSND_Harm_Buck1					,
	eSND_Harm_Buck2					,
	eSND_Harm_Buck3					,
	eSND_Harm_BuckEat				,
	eSND_Harm_JaBuck				,
	eSND_Harm_DaDack				,
	eSND_Harm_Zock					,
	eSND_Harm_SackSul				,
	eSND_Harm_Shake					,
	eSND_Harm_Bonus					,
	eSND_Harm_Bomb					,
	eSND_Harm_3Gwang				,
	eSND_Harm_4Gwang				,
	eSND_Harm_5Gwang				,
	eSND_Harm_BGwang				,
	eSND_Harm_1Go					,
	eSND_Harm_2Go					,
	eSND_Harm_3Go					,
	eSND_Harm_4Go					,
	eSND_Harm_5Go					,
	eSND_Harm_6Go					,
	eSND_Harm_7Go					,
	eSND_Harm_8Go					,
	eSND_Harm_Godori				,
	eSND_Harm_ChoDan				,
	eSND_Harm_HongDan				,
	eSND_Harm_ChungDan				,
	eSND_Harm_ChongTong				,

	eSND_Etc_Click					,
	eSND_Etc_Focus					,
	eSND_Etc_Page					,
	eSND_Etc_Notice1				,
	eSND_Etc_Notice2				,
	eSND_Etc_Ladder					,

	eIMG_BG_Splash					,
	eIMG_BG_Start					,
	eIMG_BG_Start2					,
	eIMG_BG_Stage					,
	eIMG_BG_Request1				,
	eIMG_BG_Request2				,
	eIMG_BG_Dlg_Config				,
	eIMG_BG_Dlg_Multi1				,
	eIMG_BG_Dlg_Multi2				,
	eIMG_BG_Dlg_Info				,
	eIMG_BG_Dlg_Rank				,
	eIMG_BG_Dlg_List				,
	eIMG_BG_Dlg_Shop				,
	eIMG_BG_Dlg_Shop2				,
	eIMG_BG_Dlg_Shop3				,
    eIMG_BG_Dlg_Game                ,
	eIMG_BG_List_Rank				,
	eIMG_BG_Game					,
	eIMG_BG_Result					,
	eIMG_BG_Ladder					,

	eIMG_BTN_Quit_Nor				,
	eIMG_BTN_Quit_Sel				,
	eIMG_BTN_Config_Nor			    ,
	eIMG_BTN_Config_Sel			    ,
	eIMG_BTN_Game_Nor               ,
	eIMG_BTN_Game_Sel               ,
	eIMG_BTN_Rank_Nor               ,
	eIMG_BTN_Rank_Sel               ,
	eIMG_BTN_Help_Nor               ,
	eIMG_BTN_Help_Sel               ,
	eIMG_BTN_Main_Nor               ,
	eIMG_BTN_Main_Sel               ,
	eIMG_BTN_Info_Nor               ,
	eIMG_BTN_Info_Sel               ,
	eIMG_BTN_Shop_Nor               ,
	eIMG_BTN_Shop_Sel               ,
    eIMG_BTN_Close_Nor              ,
    eIMG_BTN_Close_Sel              ,    
	eIMG_BTN_Prev_Nor               ,
	eIMG_BTN_Prev_Sel               ,
	eIMG_BTN_Next_Nor               ,
	eIMG_BTN_Next_Sel               ,
	eIMG_BTN_Yes_Nor                ,
	eIMG_BTN_Yes_Sel                ,
	eIMG_BTN_No_Nor                 ,
	eIMG_BTN_No_Sel                 ,
	eIMG_BTN_Confirm_Nor			,
	eIMG_BTN_Confirm_Sel			,
	eIMG_BTN_Reset_Nor              ,
	eIMG_BTN_Reset_Sel              ,
	eIMG_BTN_Mini_Game_Nor			,
	eIMG_BTN_Mini_Game_Sel			,
	eIMG_BTN_On_Nor                 ,
	eIMG_BTN_Off_Nor                ,
	eIMG_BTN_1_Nor					,
	eIMG_BTN_1_Sel					,
	eIMG_BTN_2_Nor					,
	eIMG_BTN_2_Sel					,
	eIMG_BTN_3_Nor					,
	eIMG_BTN_3_Sel					,
	eIMG_BTN_Circle_Nor             ,
	eIMG_BTN_Circle_Sel             ,
	eIMG_BTN_Connect_Nor            ,
	eIMG_BTN_Connect_Sel            ,
	eIMG_BTN_Buy_Nor                ,
	eIMG_BTN_Buy_Sel                ,
	eIMG_BTN_Go_Nor					,
	eIMG_BTN_Go_Sel					,
	eIMG_BTN_Stop_Nor				,
	eIMG_BTN_Stop_Sel				,
	eIMG_BTN_ChongTong_Go_Nor		,
	eIMG_BTN_ChongTong_Go_Sel		,
	eIMG_BTN_ChongTong_Stop_Nor		,
	eIMG_BTN_ChongTong_Stop_Sel		,
	eIMG_BTN_Gukjin_10_Nor			,
	eIMG_BTN_Gukjin_10_Sel			,
	eIMG_BTN_Gukjin_2_Nor			,
	eIMG_BTN_Gukjin_2_Sel			,
	eIMG_BTN_Continue_Nor			,
	eIMG_BTN_Continue_Sel			,
	eIMG_BTN_Push_Nor				,
	eIMG_BTN_Push_Sel				,
	eIMG_BTN_Stop2_Nor				,
	eIMG_BTN_Stop2_Sel				,
	eIMG_BTN_Game_Menu1				,
	eIMG_BTN_Game_Menu2				,
	eIMG_BTN_Game_Skill1			,
	eIMG_BTN_Game_Skill2			,
	eIMG_BTN_Game_Help_Nor			,
	eIMG_BTN_Game_Setting_Nor		,
	eIMG_BTN_Game_Shop_Nor			,
	eIMG_BTN_Game_Help_Sel			,
	eIMG_BTN_Game_Setting_Sel		,
	eIMG_BTN_Game_Shop_Sel			,
	eIMG_BTN_Shop_Menu_Nor			,
	eIMG_BTN_Shop_Menu_Sel			,
	eIMG_BTN_Shop_Coin_Nor			,
	eIMG_BTN_Shop_Coin_Sel			,
	eIMG_BTN_Shop_Cash_Nor			,
	eIMG_BTN_Shop_Cash_Sel			,

	eIMG_ETC_Coin					,
    eIMG_ETC_Text_Input             ,
	eIMG_ETC_Game_Info				,
	eIMG_ETC_Page_Mark_Nor			,
	eIMG_ETC_Page_Mark_Sel			,
	eIMG_ETC_Progress1				,
	eIMG_ETC_Progress2				,
	eIMG_ETC_Star1					,
	eIMG_ETC_Star2					,
	eIMG_ETC_Talk1					,
	eIMG_ETC_Talk2					,
	eIMG_ETC_Stage_Menu_Border1		,
	eIMG_ETC_Stage_Menu_Border2		,
	eIMG_ETC_Title_Menu_Border		,
	eIMG_ETC_Skill_Menu_Border1		,
	eIMG_ETC_Skill_Menu_Border2		,
	eIMG_ETC_Skill_Menu_Border3		,
	eIMG_ETC_First_Player1			,
	eIMG_ETC_First_Player2			,
	eIMG_ETC_Player_Arrow1			,
	eIMG_ETC_Player_Arrow2			,
	eIMG_ETC_Mission_X				,
	eIMG_ETC_Mission_Arrow1			,
	eIMG_ETC_Mission_Arrow2			,
	eIMG_ETC_Mission_Fail			,
	eIMG_ETC_Mission_Success1		,
	eIMG_ETC_Mission_Success2		,
	eIMG_ETC_Mission_Mark			,
	eIMG_ETC_Mission_Mark_Medium	,
	eIMG_ETC_Win					,
	eIMG_ETC_Lose					,
	eIMG_ETC_Bankrupted				,
	eIMG_ETC_Point_Times			,
	eIMG_ETC_Timing_Bar				,
	eIMG_ETC_Timing_Gage			,
	eIMG_ETC_Number_Box				,
	eIMG_ETC_Ladder_Notice			,
	eIMG_ETC_Ladder_Nor				,
	eIMG_ETC_Ladder_Sel				,
	eIMG_ETC_Ladder_KBM				,

	eIMG_Sprite_Main				,
	eIMG_Sprite_Versus				,
	eIMG_Sprite_Bet					,
	eIMG_Sprite_Skill				,
	eIMG_Sprite_Title_Menu_Nor		,
	eIMG_Sprite_Title_Menu_Dis		,
	eIMG_Sprite_Stage_Menu_Nor		,
	eIMG_Sprite_Stage_Menu_Dis		,
	eIMG_Sprite_Rank_Tab_Nor		,
	eIMG_Sprite_Rank_Tab_Sel		,
	eIMG_Sprite_Card				,
	eIMG_Sprite_Card_Medium			,
	eIMG_Sprite_Card_Small			,
	eIMG_Sprite_Card_Mini			,
	eIMG_Sprite_Select				,
	eIMG_Sprite_Select_Medium		,

	eIMG_Font_A						,
	eIMG_Font_C						,
	eIMG_Font_D						,
	eIMG_Font_E						,

	eIMG_Effect_Gage				,
	eIMG_Effect_Gage2				,
	eIMG_Effect_Buck				,
	eIMG_Effect_Buck2				,
	eIMG_Effect_Heading				,
	eIMG_Effect_Zack				,
	eIMG_Effect_Zock				,
	eIMG_Effect_Zock2				,
	eIMG_Effect_DaDack				,
	eIMG_Effect_SackSul				,
	eIMG_Effect_Bomb				,
	eIMG_Effect_Bell				,
	eIMG_Effect_Shine1				,
	eIMG_Effect_Shine2				,
	eIMG_Effect_Stop				,
	eIMG_Effect_1Go					,
	eIMG_Effect_2Go					,
	eIMG_Effect_3Go					,
	eIMG_Effect_4Go					,
	eIMG_Effect_5Go					,
	eIMG_Effect_6Go					,
	eIMG_Effect_7Go					,
	eIMG_Effect_8Go					,
	eIMG_Effect_3Gwang				,
	eIMG_Effect_4Gwang				,
	eIMG_Effect_5Gwang				,
	eIMG_Effect_BGwang				,
	eIMG_Effect_ChoDan				,
	eIMG_Effect_HongDan				,
	eIMG_Effect_ChungDan			,
	eIMG_Effect_Godori				,
	eIMG_Effect_MissionS			,
	eIMG_Effect_MissionF			,
};

enum EText
{
	eTXT_Nim						,
    eTXT_Sojigum                    ,
	eTXT_Won						,
    eTXT_Money                      ,
    eTXT_Coin                       ,
    eTXT_Point                      ,
    eTXT_Unit                       ,
	eTXT_Win1						,
    eTXT_Win2                       ,
	eTXT_Lose1						,
    eTXT_Lose2                      ,
    eTXT_Go                         ,    
	eTXT_Buy						,
    eTXT_Select                     ,
    eTXT_Skill                      ,
    eTXT_Use                        ,
    eTXT_First                      ,
    eTXT_Combo                      ,
    eTXT_Has_Coin                   ,
    eTXT_Nagari                     ,
    eTXT_Nagari_Desc                ,
    eTXT_This_Game                  ,
    eTXT_Push_Player                ,
    eTXT_Push_Enemy                 ,
    eTXT_Push_Desc                  ,
    eTXT_Current                    ,
    eTXT_Max                        ,
    eTXT_Mission                    ,
    eTXT_ChongTong                  ,
    eTXT_GukJin                     ,
    eTXT_BGwang                     ,
    eTXT_3Gwang                     ,
    eTXT_4Gwang                     ,
    eTXT_5Gwang                     ,
    eTXT_Godori                     ,
    eTXT_ChoDan                     ,
    eTXT_HongDan                    ,
    eTXT_ChungDan                   ,
    eTXT_GwangBak                   ,
    eTXT_MungBak                    ,
    eTXT_PiBak                      ,
    eTXT_GoBak                      ,
    eTXT_Gage                       ,
	eTXT_10Pi						,
	eTXT_5Pi						,
	eTXT_Pi							,
    eTXT_Card                       ,
    eTXT_Buck                       ,
    eTXT_Shake                      ,
    eTXT_Push                       ,
    eTXT_Times                      , 
    eTXT_Request                    ,
    eTXT_Able                       ,
    eTXT_Obtain                     ,
    eTXT_Prize                      ,
    eTXT_Losing                     ,
    eTXT_Bankrupt_Desc1             ,
    eTXT_Bankrupt_Desc2             ,
    eTXT_Obtain_Coin                ,
    eTXT_Obtain_Cash                ,
    eTXT_Max_Cash                   ,
    eTXT_Max_Score                  ,
    eTXT_My_Order                   ,
    eTXT_Title                      ,
    eTXT_LevelUp                    ,
    
    eTXT_Title_Notice               ,
    eTXT_Title_Bankrupt             ,
    eTXT_Title_Exit                 ,
    eTXT_Title_Config               ,
    eTXT_Title_Info1                ,
    eTXT_Title_Info2                ,
    eTXT_Title_Info3                ,
    eTXT_Title_Shop                 ,
    eTXT_Title_Shop_Coin            ,
    eTXT_Title_Shop_Cash            ,
    eTXT_Title_Shop_Skill           ,
    eTXT_Title_Rank                 ,
    eTXT_Title_Rank2                ,
    eTXT_Title_NickName             ,
    eTXT_Title_Use_Skill            ,
    eTXT_Title_Push                 ,
    eTXT_Title_Reward               ,
    eTXT_Title_Help1                ,
    eTXT_Title_Help2                ,
    eTXT_Title_Help3                ,
    eTXT_Title_Help4                ,
    eTXT_Title_Help5                ,
    eTXT_Title_Help6                ,
    eTXT_Title_Help7                ,
    eTXT_Title_Help8                ,
    eTXT_Title_Help9                ,
    eTXT_Title_Help10               ,
    eTXT_Title_Help11               ,
    
    eTXT_Notice_Network             ,
    eTXT_Notice_Network_Fail        ,
    eTXT_Request_Activate           ,
    eTXT_Request_Activate2          ,
    eTXT_Request_SMS                ,
    eTXT_Notice_Start               ,
    eTXT_Request_Reset_Game         ,
    eTXT_Request_Rank               ,
    eTXT_Request_Quit               ,
    eTXT_Notice_NickName            ,
    eTXT_Notice_NickName2           ,
    eTXT_Notice_Input_Limit         ,
    eTXT_Request_Buy                ,  
    eTXT_Notice_Pay                 , 
    eTXT_Notice_Buy_Done            ,    
    eTXT_Notice_Buy_Fail            ,    
    eTXT_Notice_Not_Enough          ,    
    eTXT_Select_Title               ,
    eTXT_Select_Skill_None          ,
    eTXT_Select_Skill_Desc          ,
    eTXT_Select_Skill_Buy			,

	eTXT_Name_KBM					,

	eTXT_Title_Name0				,
	eTXT_Title_Name1				,
	eTXT_Title_Name2				,
	eTXT_Title_Name3				,
	eTXT_Title_Name4				,

    eTXT_Title_Desc1                ,
    eTXT_Title_Desc2                ,
    eTXT_Title_Desc3                ,
    eTXT_Title_Desc4                ,
    
	eTXT_Enemy_Name1				,
	eTXT_Enemy_Name2				,
	eTXT_Enemy_Name3				,
	eTXT_Enemy_Name4				,
	eTXT_Enemy_Name5				,
	eTXT_Enemy_Name6				,
	eTXT_Enemy_Name7				,
	eTXT_Enemy_Name8				,
	eTXT_Enemy_Name9				,

	eTXT_Level_Name1				,
	eTXT_Level_Name2				,
	eTXT_Level_Name3				,
	eTXT_Level_Name4				,
	eTXT_Level_Name5				,
	eTXT_Level_Name6				,
	eTXT_Level_Name7				,
	eTXT_Level_Name8				,
	eTXT_Level_Name9				,
	eTXT_Level_Name10				,

	eTXT_Skill_Name1				,
	eTXT_Skill_Name2				,
	eTXT_Skill_Name3				,
	eTXT_Skill_Name4				,
	eTXT_Skill_Name5				,
	eTXT_Skill_Name6				,
	eTXT_Skill_Name7				,
	eTXT_Skill_Name8				,
	eTXT_Skill_Name9				,
	eTXT_Skill_Name10				,

	eTXT_Skill_Desc1                ,
	eTXT_Skill_Desc2                ,
	eTXT_Skill_Desc3                ,
	eTXT_Skill_Desc4                ,
	eTXT_Skill_Desc5                ,
	eTXT_Skill_Desc6                ,
	eTXT_Skill_Desc7                ,
	eTXT_Skill_Desc8                ,
	eTXT_Skill_Desc9                ,
	eTXT_Skill_Desc10               ,
    
    eTXT_Config_Speed               , 
    eTXT_Config_Sound               ,
    eTXT_Config_Voice               ,
    eTXT_Config_Vibration           ,
    eTXT_Config_Reset               ,
    eTXT_Config_Game_Reset          ,
};

enum ETalk
{
    eTALK_Take                      ,  
    eTALK_Zock                      ,
    eTALK_SackSul                   ,
    eTALK_DaDack                    ,
    eTALK_Buck                      ,
    eTALK_JaBuck                    ,
    eTALK_Bomb                      ,
    eTALK_1Go                       ,
    eTALK_3Go                       ,
    eTALK_5Go                       ,
    eTALK_6Go                       ,
    eTALK_7Go                       ,
    eTALK_8Go                       ,
    eTALK_ChoDan                    ,
    eTALK_HongDan                   ,
    eTALK_ChungDan                  ,
    eTALK_Godori                    ,
    eTALK_3Gwang                    ,
    eTALK_5Gwang                    ,
    eTALK_BGwang                    ,
    eTALK_ChongTong                 ,
    eTALK_Stop                      ,
    eTALK_Heading                   ,
    eTALK_Gage1                     ,
    eTALK_Gage2                     ,
    eTALK_Gage3                     ,    
    eTALK_Slow                      ,
    eTALK_Limit                     ,
};

class CResManager
{
	protected :

		 CResManager ( KDvoid );
		~CResManager ( KDvoid );

	public :

		static KDvoid  create  ( KDvoid );
		static KDvoid  release ( KDvoid );

	public :

		const KDchar*  getPath			( EPath eID );
		const KDchar*  getPath			( EPath eID, KDuint uIndex );
		const KDchar*  getPathSprite	( EPath eID, KDuint uIndex );
        const KDchar*  getPathCharacter ( KDuint uIndex, KDuint uState );
		const KDchar*  getPathCartoon	( KDuint uStage, KDuint uIndex, KDbool bOpenning = KD_TRUE );

        const KDchar*  getText			( EText eID );
        const KDchar*  getText          ( EText eID, KDuint uIndex );
        const KDchar*  getTextHelp      ( KDuint uIndex );
    
        const KDchar*  getPathTalk      ( ETalk eID, KDuint uIndex, KDuint uState );
        const KDchar*  getTextTalk      ( ETalk eID, KDuint uIndex, KDuint uState );
        
		KDvoid  playSound ( EPath eID, KDint nMode = CCSoundEffect );
		KDvoid  stopSound ( EPath eID );

		KDvoid	playBGM   ( EPath eID );
		KDvoid	stopBGM   ( KDvoid );
		KDvoid	pauseBGM  ( KDvoid );
		KDvoid  resumeBGM ( KDvoid );

		KDvoid  vibrate   ( KDvoid );

	protected :

		EPath			m_eBGM;
};

extern CResManager*  g_pResManager;

#endif
